### ISSUE TITLE
Cannot see SnapCI?

### ISSUE THREAD

**Issue by kentcdodds** [willbuck/midwestjs-2015-protractor#1]
For some reason, when I click your snap badge, this is all I see:

![screen shot 2015-08-17 at 1 17 57 pm](https://cloud.githubusercontent.com/assets/1500684/9313830/6aaf0f64-44e2-11e5-92b7-20f57fd2c8e1.png)

All I really want to see is your stages and the commands in there. Do you mind sharing those?

**Comment by willbuck** [comment]
Don't mind at all @kentcdodds! On my phone right now but I'll take a look and see why the badge is broken, and if I can't fix it I'll close this issue with details on the stages I had configured!

**Comment by willbuck** [comment]
Hey @kentcdodds! I found the issue, I had renamed this repo about a week or so before the conference, so the badge link to SnapCI was pointed at the old name! Link should be repaired and you can see the command output in there! See https://github.com/willbuck/midwestjs-2015-protractor/pull/2

In case you or someone else doesn't want to trog through the log output though, essentially both stages (the one for midwestjs and prizeotron) are just doing 

```
npm install
 ./node_modules/protractor/bin/webdriver-manager update
./node_modules/protractor/bin/protractor snapci.conf.js --suite $SUITENAME
```

I have the first two commands 'pinned' between the two stages, it looks like Snap is caching node_modules as a result so npm install is probably just costing file copy time (no idea really though), and then the only other tweaks are
- Both 'stages' archive the ./target folder, where I'm saving the screenshots, and
- The prizeotron suite is getting passed my main.secrets.js with my real Meetup.com API key and event ID in it

Feel free to re-open / submit more issues if you have any other problems, really appreciate you finding this bug Kent!

**Comment by kentcdodds** [comment]
Thanks @willbuck! cc/ @paraplexed
